spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springboot_db
        username: root
        password: root
        platform: mysql
        initialize: false
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: create
        show-sql: true

---
spring:
    profiles: container
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        initialize: true